CREATE TABLE groups (
    id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    name VARCHAR2(50) NOT NULL,
    students_count NUMBER(10) NOT NULL
);

CREATE TABLE courses (
    id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    name VARCHAR2(50) NOT NULL,
    professor VARCHAR2(50)
);

CREATE TABLE students (
    id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    name VARCHAR2(50) NOT NULL,
    group_id NUMBER(10),
    enter_date TIMESTAMP DEFAULT CURRENT_DATE
);

DROP TABLE courses;
DROP TABLE students;
DROP TABLE groups;


CREATE OR REPLACE TRIGGER group_size_iterator
AFTER INSERT OR DELETE ON students
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        UPDATE groups
        SET groups.students_count = groups.students_count + 1
        WHERE id = :NEW.group_id;
    ELSE
        UPDATE groups
        SET groups.students_count = groups.students_count - 1
        WHERE id = :OLD.group_id;
    END IF;
END;
/

-- Fill Tables
INSERT INTO students (name, group_id) VALUES ('Vasya', 1);
BEGIN
    INSERT INTO students (name, group_id) VALUES ('Vasya', 1);
    DBMS_SESSION.SLEEP(2);
    INSERT INTO students (name, group_id) VALUES ('Petya', 2);
    DBMS_SESSION.SLEEP(2);
    INSERT INTO students (name, group_id) VALUES ('Tanya', 3);
    DBMS_SESSION.SLEEP(2);
    INSERT INTO students (name, group_id) VALUES ('Sasha', 2);
    DBMS_SESSION.SLEEP(2);
    INSERT INTO students (name, group_id) VALUES ('John', 1);
    DBMS_SESSION.SLEEP(2);
    INSERT INTO students (name, group_id) VALUES ('Selivan', 1);
END;
/

INSERT INTO groups (name, students_count) VALUES ('Mathematic2.0', 0);
BEGIN
    INSERT INTO groups (name, students_count) VALUES ('Mathematic', 0);
    DBMS_SESSION.SLEEP(2);
    INSERT INTO groups (name, students_count) VALUES ('Physics', 0);
    DBMS_SESSION.SLEEP(2);
    INSERT INTO groups (name, students_count) VALUES ('Geography', 0);
    DBMS_SESSION.SLEEP(2);
    INSERT INTO groups (name, students_count) VALUES ('Music', 0);
END;
/

INSERT INTO courses (name, professor) VALUES ('MTRAN', 'Shimanskij');
INSERT INTO courses (name, professor) VALUES ('ITIROD', 'Zhvakina');